#!/usr/bin/env bash
# SCAS full stack: labs env + Elasticsearch + Kibana + Floci + act check + dashboard UI.
#
# One command from the repo root (Docker Desktop must be running):
#   ./scripts/ui/run-everything.sh
#
# Flags:
#   --skip-es      skip Elasticsearch/Kibana
#   --skip-floci   skip Floci
#   --skip-setup   skip ./scripts/setup/setup.sh + npm install
#   --skip-act     allow start without nektos/act (labs 05/25 may use npm fallback)
#   --no-ui        bring platform up only (no dashboard)
#   --core-only    labs + UI only (implies --skip-es --skip-floci)
#
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT"

SKIP_ES=0
SKIP_FLOCI=0
SKIP_SETUP=0
SKIP_ACT=0
NO_UI=0

for arg in "$@"; do
  case "$arg" in
    --skip-es) SKIP_ES=1 ;;
    --skip-floci) SKIP_FLOCI=1 ;;
    --skip-setup) SKIP_SETUP=1 ;;
    --skip-act) SKIP_ACT=1 ;;
    --no-ui) NO_UI=1 ;;
    --core-only) SKIP_ES=1; SKIP_FLOCI=1 ;;
    -h|--help)
      awk 'NR==1{next} /^#/{sub(/^# ?/,""); print; next} {exit}' "$0"
      exit 0
      ;;
    *)
      echo "Unknown option: $arg" >&2
      exit 1
      ;;
  esac
done

log()  { printf '▶ %s\n' "$*"; }
ok()   { printf '✓ %s\n' "$*"; }
warn() { printf '! %s\n' "$*" >&2; }

need_docker() {
  if ! command -v docker >/dev/null 2>&1; then
    warn "Docker CLI not found. Install Docker Desktop."
    exit 1
  fi
  if ! docker info >/dev/null 2>&1; then
    warn "Docker daemon is not running. Open Docker Desktop and wait until it is idle, then re-run."
    exit 1
  fi
  ok "Docker is running"
}

ensure_act() {
  chmod +x scripts/setup/ensure-act.sh
  # Always prefer repo-local .tools/bin when present
  if [[ -d "${ROOT}/.tools/bin" ]]; then
    export PATH="${ROOT}/.tools/bin:${PATH}"
  fi
  if [[ "$SKIP_ACT" = "1" ]]; then
    if ./scripts/setup/ensure-act.sh --check; then
      ok "act present (optional --skip-act ignored for status)"
    else
      warn "act missing; continuing because --skip-act was set (labs 05/25 may use npm fallback)"
    fi
    return 0
  fi
  log "Ensuring nektos/act for labs 05 and 25…"
  ./scripts/setup/ensure-act.sh
  export PATH="${ROOT}/.tools/bin:${PATH}"
  hash -r 2>/dev/null || true
}

write_session_env() {
  local env_file="${ROOT}/.scas.env"
  local act_required=0
  if command -v act >/dev/null 2>&1 && act --help 2>/dev/null | grep -q -- '--local-repository'; then
    act_required=1
  fi
  {
    cat <<'EOF'
# SCAS session environment - generated by scripts/ui/run-everything.sh
# Usage: source .scas.env

_SCAS_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)"

# Repo-local tools (nektos/act from ensure-act.sh)
if [ -d "${_SCAS_ROOT}/.tools/bin" ]; then
  export PATH="${_SCAS_ROOT}/.tools/bin:${PATH}"
fi

if [ -f "${_SCAS_ROOT}/.testbench.env" ]; then
  # shellcheck disable=SC1091
  source "${_SCAS_ROOT}/.testbench.env"
fi
export TESTBENCH_MODE="${TESTBENCH_MODE:-enabled}"
export SCAS_REPO_ROOT="${_SCAS_ROOT}"

EOF
    if [[ "$act_required" = "1" ]]; then
      cat <<'EOF'
# Prefer real act workflows for labs 05/25 (set SCAS_SKIP_ACT=1 to force npm stand-in)
export SCAS_ACT_REQUIRED="${SCAS_ACT_REQUIRED:-1}"

EOF
    fi
    if [[ "$SKIP_ES" != "1" ]]; then
      cat <<'EOF'
export SCAS_ES_URL="${SCAS_ES_URL:-http://127.0.0.1:9200}"
export KIBANA_URL="${KIBANA_URL:-http://127.0.0.1:5601}"

EOF
    fi
    if [[ "$SKIP_FLOCI" != "1" ]]; then
      cat <<'EOF'
if [ -f "${_SCAS_ROOT}/.floci.env" ]; then
  # shellcheck disable=SC1091
  source "${_SCAS_ROOT}/.floci.env"
fi

EOF
    fi
    cat <<'EOF'
unset _SCAS_ROOT
EOF
  } >"${env_file}"
  ok "Wrote ${env_file}"
}

print_status() {
  echo ""
  echo "Stack status"
  if curl -fsS "http://127.0.0.1:9200/_cluster/health" >/dev/null 2>&1; then
    ok "Elasticsearch  http://127.0.0.1:9200"
  else
    warn "Elasticsearch  down"
  fi
  if curl -fsS -o /dev/null "http://127.0.0.1:5601" 2>/dev/null; then
    ok "Kibana         http://127.0.0.1:5601"
  else
    warn "Kibana         down"
  fi
  if curl -fsS -o /dev/null "http://127.0.0.1:4566/_floci/health" 2>/dev/null || \
     curl -fsS -o /dev/null "http://127.0.0.1:4566" 2>/dev/null; then
    ok "Floci          http://127.0.0.1:4566"
  else
    warn "Floci          down"
  fi
  if command -v act >/dev/null 2>&1 && act --help 2>/dev/null | grep -q -- '--local-repository'; then
    ok "act            $(act --version 2>/dev/null | head -1) (labs 05/25 use real workflows)"
  else
    warn "act            missing"
  fi
  echo ""
}

# --- main ---

log "SCAS full stack from ${ROOT}"

if [[ "$SKIP_ES" != "1" || "$SKIP_FLOCI" != "1" ]]; then
  need_docker
fi

if [[ "$SKIP_SETUP" != "1" ]]; then
  log "Core setup (TESTBENCH + npm workspaces)…"
  chmod +x scripts/setup/setup.sh
  ./scripts/setup/setup.sh
  if [[ ! -d node_modules ]]; then
    npm install
  fi
  ok "Core setup done"
else
  warn "Skipping setup (--skip-setup)"
fi

ensure_act

if [[ "$SKIP_ES" != "1" ]]; then
  log "Starting Elasticsearch + Kibana (templates, runbooks, Kibana views, capture backfill)…"
  chmod +x scripts/observability/elasticsearch-up.sh
  ./scripts/observability/elasticsearch-up.sh
  # Ensure session + child processes see ES even if elasticsearch-up used localhost vs 127.0.0.1
  export SCAS_ES_URL="${SCAS_ES_URL:-http://127.0.0.1:9200}"
  export KIBANA_URL="${KIBANA_URL:-http://127.0.0.1:5601}"
else
  warn "Skipping Elasticsearch (--skip-es)"
fi

if [[ "$SKIP_FLOCI" != "1" ]]; then
  log "Configuring / starting Floci…"
  chmod +x scripts/floci/floci-setup.sh scripts/floci/floci-up.sh
  if [[ ! -f "${ROOT}/.floci.env" ]] && [[ ! -f "${ROOT}/infrastructure/floci/.env" ]]; then
    ./scripts/floci/floci-setup.sh --auto || ./scripts/floci/floci-setup.sh --image || true
  fi
  if ! ./scripts/floci/floci-up.sh; then
    warn "Floci failed to start. Labs still work; cloud-track needs Floci later."
  fi
else
  warn "Skipping Floci (--skip-floci)"
fi

write_session_env
# shellcheck disable=SC1091
source "${ROOT}/.scas.env"

print_status

if [[ "$NO_UI" = "1" ]]; then
  ok "Platform up. Source env and run a lab:"
  echo "  source .scas.env"
  echo "  cd scenarios/01-typosquatting && ./setup.sh"
  exit 0
fi

log "Starting dashboard (control plane inherits SCAS_ES_URL / Floci env)…"
chmod +x scripts/ui/start-dashboard.sh
exec ./scripts/ui/start-dashboard.sh
